name: Deploy Vite

on:
  push:
    branches:
      - main
      - preview

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy_gh_pages:
    name: Deploy to GitHub Pages
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/preview'

    steps:
      - name: Download production files
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Copy preview files
        run: cp -r preview/* ./production-files
        if: github.ref == 'refs/heads/preview'

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update gh-pages with main and preview files"
          git push origin HEAD

